version: '2.1'
services:
  filebrowser:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ~/your-data-folder:/srv         # You can replace this "~/your-data-folder" with your own folder
      - ./filebrowser.db:/database.db
    ports:
      - '8080:80'
    image: filebrowser:v1
